Start with standard integration tests using integration-test-commons
stackabletech/spark-operator-integration-tests pull request #3
Opened 2021-06-21 08:33 UTC by maltesander

Currently, the integration tests cover the following cases:

- **Create** a Spark cluster and check if it is running correctly
- **Update** a Spark cluster from version 3.0.1 to 3.1.1 and check if it is running correctly
- **Scale** a Spark cluster up (e.g. from 1 to 2 workers) and down (e.g. from 2 to 1 workers)
- **Restart** a Spark cluster via Restart command

2021-07-30 11:59 UTC, soenkeliebau reviewed
Just some initial comments I had looking over this. Haven't properly tested it yet, as it requires the PR on the spark-operator to be updated to the new operator framework.

2021-07-30 15:59 UTC, maltesander commented on tests/restart_cluster.rs
> +    cluster.wait_ready(expected_pod_count)?;
The apply_command has a 2 second sleep to give the operator time to react.

2021-07-30 15:59 UTC, maltesander commented on tests/restart_cluster.rs
> +    // TODO: Check if label done exists in command
Yeah that makes sense.

2021-08-12 12:07 UTC, lfrancke requested changes
I have pushed a single commit to fix the CI and PR template stuff.
And I have two comments.

2021-08-12 12:07 UTC, lfrancke commented on tests/restart_cluster.rs
> +    cluster.wait_ready(expected_pod_count)?;
Also: This will not check if a restart was running at all....shouldn't we maybe check the timestamps of the containers or something similar?

2021-08-12 12:07 UTC, lfrancke commented on tests/update_cluster.rs
> +    cluster.create_or_update(&spark_cr, expected_pod_count)
This doesn't check whether the version update actually did anything, does it?

2021-08-19 09:12 UTC, maltesander commented on tests/restart_cluster.rs
> +    cluster.wait_ready(expected_pod_count)?;
Yeah it only checks if pods are coming up again. I am not sure how to handle the timestamps (since pods come up after each other, have different names, timestamps etc.). Will be cumbersome to check that afterwards. What about storing the uids and check if no uids match afterwards? That would ensure that every pod was cleaned up and restarted?

2021-08-19 09:20 UTC, soenkeliebau commented on tests/restart_cluster.rs
> +    cluster.wait_ready(expected_pod_count)?;
An alternative might be to compare each pods creation_timestamp with the commands creation_timestamp, success criteria should be that all pods have `pod.creation_timestamp > command.creation_timestamp && pod.status == running`  - would that work?

2021-08-19 09:47 UTC, lfrancke commented on tests/restart_cluster.rs
> +    cluster.wait_ready(expected_pod_count)?;
Yeah, I was thinking about @soenkeliebau 's solution as well.

2021-08-23 08:49 UTC, lfrancke approved these changes

2021-08-23 09:00 UTC, merged