Added files to run integration tests with Stackable CI infrastructure
stackabletech/spark-operator-integration-tests pull request #8
Opened 2021-09-16 16:27 UTC by backstreetkiwi

## Description
The integration tests are now run in the new CI (https://ci.stackable.tech). The files in the .ci/ folder contain the cluster definition and test script.

## Review Checklist
- [ ] Code contains useful comments

2021-09-16 17:00 UTC, maltesander submitted a review, later dismissed
LGTM.

2021-09-16 17:15 UTC, backstreetkiwi commented
Sorry, @maltesander, I just added the node labels because I hope this makes the test successful...

2021-09-16 17:22 UTC, maltesander requested changes

2021-09-16 17:22 UTC, maltesander commented on .ci/integration-tests/aws-centos-8/test.sh
> +/stackable.sh testdriver-1 -i /.cluster/key 'kubectl label node main-3.stackable.test node=3'
Spark never needed that? I think it was only zookeeper?

2021-09-16 18:14 UTC, backstreetkiwi commented on .ci/integration-tests/aws-centos-8/test.sh
> +/stackable.sh testdriver-1 -i /.cluster/key 'kubectl label node main-3.stackable.test node=3'
It was just a desperate try, I copied it from ZooKeeper ;-)

2021-09-16 18:19 UTC, backstreetkiwi commented on .ci/integration-tests/aws-centos-8/test.sh
> +/stackable.sh testdriver-1 -i /.cluster/key 'kubectl label node main-3.stackable.test node=3'
I will revert that change.

2021-09-17 10:28 UTC, maltesander approved these changes
LGTM.

2021-09-17 10:30 UTC, merged